### ISSUE TITLE
Version for torchmetrics

### ISSUE THREAD

**Issue by DhavalTaunk08** [allenai/PRIMER#8]
Hi,

I am getting the below error while using the code to train the model.

```
Traceback (most recent call last):
  File "script/primer_main.py", line 1, in <module>
    from pytorch_lightning.accelerators import accelerator
  File "/home2/dhaval.taunk/miniconda3/envs/joint_gt/lib/python3.7/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/home2/dhaval.taunk/miniconda3/envs/joint_gt/lib/python3.7/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/home2/dhaval.taunk/miniconda3/envs/joint_gt/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/home2/dhaval.taunk/miniconda3/envs/joint_gt/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics
  File "/home2/dhaval.taunk/miniconda3/envs/joint_gt/lib/python3.7/site-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/home2/dhaval.taunk/miniconda3/envs/joint_gt/lib/python3.7/site-packages/torchmetrics/utilities/data.py)
```

Which version of torchmetrics is supposed to be installed? No information is being provided related to the torchmetrics version in requirements.txt

**Comment by Wendy-Xiao** [comment]
Hi,

it seems like the problem is the dependency of pytorch_lightning, which version of pytorch_lightning are you using? How did you install it? I did not install torchmetrics individually, I think it is installed as a dependency package when I install other packages. 

I would suggest you to create a new virtual environment, and install all the packages following the instructions. Or making it easier, you can directly use the hugging face version model with any version of huggingface with support for LED model.

**Comment by DhavalTaunk08** [comment]
I am using the same version which is mentioned in the requirements.txt file i.e. 1.3.5.

**Comment by armancohan** [comment]
What is your `torchmetrics` version? Can you downgrade to `0.6.0` and try again?

**Comment by DhavalTaunk08** [comment]
It is automatically installing 0.8.0. Will try with 0.6.0. Ig is should be mentioned in the requirements.txt if that is the issue.

**Comment by amelieyu1989** [comment]
meet the same issue and it does not work with torchmetrics = 0.6.0

**Comment by raymondsim** [comment]
Might be a bit late, I downgraded it to 0.5.0 and it fixes the issue.
